#!/usr/bin/env python3
"""
Heat diffusion visualization from binary files generated by the stencil simulation.

This script reads plane_XXXXX.bin files generated with the -o 1 option and creates:
- Individual frames of the diffusion
- An animated GIF
- A plot of total energy over time

Usage:
    python scripts/other/visualize_heat_diffusion.py [--output OUTPUT_DIR]
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.colors import LogNorm
import glob
import os
import argparse
from pathlib import Path

def read_plane_binary(filename, shape):
    """
    Reads a binary file plane_XXXXX.bin.
    
    Format: float32, row-major order (C style)
    """
    try:
        data = np.fromfile(filename, dtype=np.float32)
        if len(data) != shape[0] * shape[1]:
            # Try to infer shape from data
            total = len(data)
            # Assume square if possible
            side = int(np.sqrt(total))
            if side * side == total:
                shape = (side, side)
            else:
                # Try common aspect ratios
                for w in range(100, 10000):
                    if total % w == 0:
                        h = total // w
                        shape = (h, w)
                        break
        
        return data.reshape(shape)
    except Exception as e:
        print(f"Error reading {filename}: {e}")
        return None

def infer_grid_shape(filename):
    """
    Attempts to infer the grid shape from the file.
    """
    data = np.fromfile(filename, dtype=np.float32)
    total = len(data)
    
    # Try square shape
    side = int(np.sqrt(total))
    if side * side == total:
        return (side, side)
    
    # Try common shapes
    for w in [100, 200, 500, 1000, 2000, 5000]:
        if total % w == 0:
            h = total // w
            if abs(h - w) < w * 0.5:  # Prefer nearly square shapes
                return (h, w)
    
    # Default: find first divisor
    for w in range(100, int(np.sqrt(total)) + 1):
        if total % w == 0:
            h = total // w
            return (h, w)
    
    return None

def find_plane_files(pattern="plane_*.bin"):
    """
    Finds all plane_*.bin files and sorts them.
    """
    files = sorted(glob.glob(pattern))
    return files

def create_visualization(output_dir="viz_output"):
    """
    Creates heat diffusion visualizations.
    """
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Set style with white background
    plt.style.use('default')
    plt.rcParams['figure.facecolor'] = 'white'
    plt.rcParams['axes.facecolor'] = 'white'
    plt.rcParams['savefig.facecolor'] = 'white'
    
    # Find files
    plane_files = find_plane_files()
    
    if not plane_files:
        print("No plane_*.bin files found!")
        print("Run first: make -f Makefile.local run_viz")
        return
    
    print(f"Found {len(plane_files)} files")
    
    # Infer grid shape from first file
    shape = infer_grid_shape(plane_files[0])
    if shape is None:
        print("Unable to determine grid shape")
        return
    
    print(f"Grid shape: {shape[0]} x {shape[1]}")
    
    # Read all data
    frames = []
    energies = []
    
    for i, filename in enumerate(plane_files):
        data = read_plane_binary(filename, shape)
        if data is not None:
            frames.append(data)
            energies.append(np.sum(data))
            
            # Save individual frame every 10 steps
            if i % 10 == 0:
                plt.figure(figsize=(10, 8))
                im = plt.imshow(data, cmap='viridis', interpolation='nearest')
                plt.colorbar(im, label='Energy')
                plt.title(f'Heat Diffusion - Step {i}')
                plt.xlabel('X')
                plt.ylabel('Y')
                plt.tight_layout()
                plt.savefig(f'{output_dir}/frame_{i:05d}.png', dpi=100)
                plt.close()
    
    if not frames:
        print("No valid data found")
        return
    
    print(f"Read {len(frames)} frames")
    
    # Plot total energy over time
    plt.figure(figsize=(12, 6))
    plt.plot(energies, 'b-', linewidth=2)
    plt.xlabel('Iteration', fontsize=12)
    plt.ylabel('Total Energy', fontsize=12)
    plt.title('Total Energy Evolution in the System', fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/energy_evolution.png', dpi=150)
    print(f"Saved: {output_dir}/energy_evolution.png")
    
    # Create animation
    print("Creating GIF animation...")
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
    fig.patch.set_facecolor('white')
    
    # Find range for consistent colorbar
    vmin = min(np.min(f) for f in frames)
    vmax = max(np.max(f) for f in frames)
    
    # Use logarithmic scale if there are large variations
    if vmax / (vmin + 1e-10) > 100:
        norm = LogNorm(vmin=max(vmin, 1e-10), vmax=vmax)
    else:
        norm = None
    
        im1 = ax1.imshow(frames[0], cmap='viridis', interpolation='nearest', norm=norm)
    plt.colorbar(im1, ax=ax1, label='Energy')
    ax1.set_title('Heat Diffusion')
    ax1.set_xlabel('X')
    ax1.set_ylabel('Y')
    
    line, = ax2.plot([], [], 'b-', linewidth=2)
    ax2.set_xlim(0, len(energies))
    ax2.set_ylim(min(energies) * 0.9, max(energies) * 1.1)
    ax2.set_xlabel('Iteration')
    ax2.set_ylabel('Total Energy')
    ax2.set_title('Energy Evolution')
    ax2.grid(True, alpha=0.3)
    
    def animate(frame_idx):
        im1.set_array(frames[frame_idx])
        line.set_data(range(frame_idx + 1), energies[:frame_idx + 1])
        fig.suptitle(f'Heat Equation Simulation - Step {frame_idx}/{len(frames)-1}', 
                     fontsize=14, fontweight='bold')
        return im1, line
    
    anim = animation.FuncAnimation(fig, animate, frames=len(frames), 
                                   interval=100, blit=True, repeat=True)
    
    # Save as GIF
    gif_path = f'{output_dir}/heat_diffusion.gif'
    anim.save(gif_path, writer='pillow', fps=10, dpi=80)
    print(f"Saved: {gif_path}")
    
    # Also save as MP4 video if ffmpeg is available
    try:
        mp4_path = f'{output_dir}/heat_diffusion.mp4'
        anim.save(mp4_path, writer='ffmpeg', fps=10, dpi=100, bitrate=2000)
        print(f"Saved: {mp4_path}")
    except Exception as e:
        print(f"Unable to save MP4 (ffmpeg not available?): {e}")
    
    plt.close()
    
    # Create multi-frame comparison
    n_frames_to_show = min(9, len(frames))
    indices = np.linspace(0, len(frames)-1, n_frames_to_show, dtype=int)
    
    fig, axes = plt.subplots(3, 3, figsize=(15, 15))
    fig.patch.set_facecolor('white')
    axes = axes.flatten()
    
    for idx, frame_idx in enumerate(indices):
        if idx < len(axes):
            im = axes[idx].imshow(frames[frame_idx], cmap='viridis', interpolation='nearest', norm=norm)
            axes[idx].set_title(f'Step {frame_idx}')
            axes[idx].axis('off')
            plt.colorbar(im, ax=axes[idx], fraction=0.046)
    
    plt.suptitle('Heat Diffusion Evolution', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{output_dir}/evolution_grid.png', dpi=150)
    print(f"Saved: {output_dir}/evolution_grid.png")
    plt.close()
    
    print(f"\nVisualization completed!")
    print(f"Files saved in: {output_dir}/")
    print(f"- energy_evolution.png: energy over time plot")
    print(f"- heat_diffusion.gif: diffusion animation")
    print(f"- evolution_grid.png: snapshot grid")
    print(f"- frame_*.png: individual frames")

def main():
    parser = argparse.ArgumentParser(
        description='Visualize heat diffusion from binary files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Use default output directory (viz_output)
  python scripts/other/visualize_heat_diffusion.py
  
  # Specify custom output directory
  python scripts/other/visualize_heat_diffusion.py --output my_results
        """
    )
    parser.add_argument('--output', '-o', default='viz_output',
                        help='Output directory for files (default: viz_output)')
    
    args = parser.parse_args()
    
    create_visualization(args.output)

if __name__ == "__main__":
    main()
